import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdtemp, mkdir, writeFile, readFile, rm, utimes, lstat, symlink } from "node:fs/promises";
import { resolve } from "node:path";
import sharp from "sharp";
import { snapshotImages, calendarDate, hashBytes, persistentPilotRoot, localPilotOutput } from "../scripts/lib/pilot-snapshot.mjs";
import { loadSnapshot, expandClassifications, renderCatalogue, sourcePreservation, derivePilot, privatePilotSite, assertPrivatePilotOutput } from "../scripts/lib/real-pilot.mjs";
import { artworkSchema, mediumLabel, publicCatalogue } from "../src/lib/catalogue.ts";
import { chromium } from "playwright";
import { prepareScreenshot, auditAccessibility } from "../scripts/lib/browser-quality.mjs";
import { specimenSite } from "./helpers/specimen-site.mjs";

test("private M09 state defaults to persistent user data while /tmp remains test scratch only", () => {
  const root = persistentPilotRoot();
  assert.ok(root.endsWith("/.local/share/jordannesbitt-art/m09") || process.env.JORDANNESBITT_M09_DATA, `unexpected persistent root: ${root}`);
  assert.ok(!root.startsWith("/tmp/"), "durable pilot default must not live under /tmp");
  assert.equal(localPilotOutput(resolve(root, "reviews")), resolve(root, "reviews"));
  assert.equal(localPilotOutput("/tmp/opencode/jordannesbitt-pilot-test"), "/tmp/opencode/jordannesbitt-pilot-test");
  assert.throws(() => localPilotOutput("/var/tmp/jordannesbitt-private"), /must stay under persistent root/);
});

test("supported-only frozen inventory preserves source mtime/bytes, dates and neutral IDs across late arrivals", async (t) => {
  const root = await mkdtemp("/tmp/opencode/jordannesbitt-pilot-test-");
  t.after(() => rm(root, { recursive: true, force: true }));
  const source = resolve(root, "source"), output = resolve(root, "private-output");
  await mkdir(source);
  const pixels = await sharp({ create: { width: 40, height: 60, channels: 3, background: "#307090" } }).jpeg().toBuffer();
  const firstFile = resolve(source, "123456789.jpg");
  await writeFile(firstFile, pixels);
  await utimes(firstFile, new Date("2020-01-02T03:00:00Z"), new Date("2020-01-02T03:00:00Z"));
  await writeFile(resolve(source, ".gallery-dl-jordancnesbitt.sqlite3"), "NON-IMAGE DATABASE SENTINEL — never decoder input");
  await writeFile(resolve(source, "invalid.jpg"), "corrupt synthetic image");
  await symlink(firstFile, resolve(source, "linked.jpg"));
  const before = await lstat(firstFile, { bigint: true });
  const first = await snapshotImages({ source, output, timezone: "America/Toronto" });
  assert.equal(first.snapshot.included.length, 1);
  assert.equal(first.snapshot.excluded.length, 1);
  assert.equal(first.snapshot.ignored.length, 2);
  const entry = first.snapshot.included[0];
  assert.equal(entry.id, "w-0001");
  assert.notEqual(entry.id, "123456789");
  assert.equal(entry.instagramFilename, "123456789.jpg");
  assert.equal(entry.provisionalCreationDate.value, "2020-01-01");
  assert.equal(entry.provisionalCreationDate.status, "provisional-owner-instructed");
  assert.equal(entry.sourceMtimeNs, before.mtimeNs.toString());
  assert.equal(entry.ownerFacts.title, null);
  assert.deepEqual(entry.ownerFacts.physicalDimensions, []);
  assert.equal(entry.ownerFacts.published, false);
  assert.equal(hashBytes(await readFile(firstFile)), hashBytes(pixels));
  assert.equal((await lstat(firstFile, { bigint: true })).mtimeNs, before.mtimeNs);
  await writeFile(resolve(source, "987654321.jpg"), pixels);
  const frozen = await loadSnapshot(resolve(first.directory, "snapshot.json"));
  assert.equal(frozen.snapshot.included.length, 1, "late export cannot enter old run");
  const second = await snapshotImages({ source, output, timezone: "America/Toronto" });
  assert.equal(second.snapshot.included.find((value) => value.file === "123456789.jpg").id, entry.id);
  assert.equal(second.snapshot.included.find((value) => value.file === "987654321.jpg").id, "w-0002");
  assert.equal((await sourcePreservation(first.snapshot)).unchanged, 1);
  await writeFile(resolve(first.directory, entry.snapshotRelativeFile), "changed frozen synthetic bytes");
  await assert.rejects(loadSnapshot(resolve(first.directory, "snapshot.json")), /Frozen image changed/);
  assert.equal(calendarDate("2020-01-02T03:00:00Z", "UTC"), "2020-01-02");
});

test("unknown medium/kind and neutral view labels do not invent physical or approval facts", () => {
  const snapshot = { snapshotSha256: "synthetic-snapshot", included: [{ id: "w-0001" }] };
  const plan = { snapshotSha256: snapshot.snapshotSha256, classifications: [{ ids: [1], medium: "unclassified", techniques: [], ambiguities: ["unknown"] }], groups: [{ id: "g-01", ids: [1], previewIds: [1], reviewLabel: "Provisional visual group G01", basis: "Review-only" }], pilotIds: [1], homepageCandidateId: 1 };
  const classes = expandClassifications(snapshot, plan);
  assert.equal(classes.get("w-0001").status, "provisional-visual-inference-not-owner-approved");
  assert.equal(mediumLabel("unclassified"), "Classification unconfirmed");
  const draft = artworkSchema.parse({ id: "w-0001", slug: "w-0001", title: "Review item w-0001 (title not supplied)", date: { certainty: "exact", year: 2020, label: "2020-01-01 — provisional file mtime" }, medium: "unclassified", kind: "unclassified", published: false, reproductions: [{ src: "/media/w-0001/test.jpg", width: 40, height: 60, role: "primary", alt: "Synthetic local test image" }] });
  const records = [{ id: "w-0001", draft, instagramFilename: "123.jpg" }];
  const rendered = renderCatalogue(records, plan);
  assert.equal(draft.published, false, "private draft remains unapproved while independent renderer uses flags");
  assert.deepEqual(rendered.artworks[0].dimensions, []);
  assert.equal(rendered.artworks[0].availability.state, "unknown");
  assert.equal(rendered.artworks[0].availability.price, undefined);
  assert.equal(rendered.artworks[0].edition, undefined);
  assert.deepEqual(publicCatalogue({ artworks: [draft], projects: [], professional: [] }).artworks, []);
  assert.throws(() => expandClassifications(snapshot, { ...plan, classifications: [] }), /needs visual inspection/);
  assert.throws(() => expandClassifications(snapshot, { ...plan, groups: [{ ...plan.groups[0], previewIds: [2] }] }), /preview sample/);
});

test("real-pilot discovered multigroup target sizing and full-page lazy image capture remain verified", async (t) => {
  const site = await specimenSite(t, (data) => { data.projects.push({ ...data.projects[0], id: "specimen-second-group", slug: "specimen-second-group", aliases: [], title: "Synthetic second group", memberIds: [data.artworks[0].id] }); return data; });
  const browser = await chromium.launch();
  t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 360, height: 800 } });
  await page.goto(`${site.origin}/archive/`);
  assert.deepEqual((await auditAccessibility(page)).violations, []);
  await page.goto(`${site.origin}/work/`);
  await prepareScreenshot(page);
  assert.ok(await page.locator("img").evaluateAll((images) => images.every((image) => image.complete && image.naturalWidth > 0)), "all below-fold images decoded for visual capture");
});

test("independent real-pilot adapter omits unapproved artist/rights/offer assertions and preserves private drafts", async (t) => {
  const root = await mkdtemp("/tmp/opencode/jordannesbitt-private-adapter-test-");
  t.after(() => rm(root, { recursive: true, force: true }));
  const source = resolve(root, "source");
  await mkdir(source);
  await writeFile(resolve(source, "123.jpg"), await sharp({ create: { width: 40, height: 60, channels: 3, background: "#606f70" } }).jpeg().toBuffer());
  const { snapshot, directory } = await snapshotImages({ source, output: resolve(root, "private"), timezone: "UTC" });
  const plan = { snapshotSha256: snapshot.snapshotSha256, classifications: [{ ids: [1], medium: "unclassified", techniques: [], ambiguities: ["Not confirmed"] }], groups: [{ id: "g-01", ids: [1], previewIds: [1], reviewLabel: "Provisional visual group G01", basis: "Local layout test" }], pilotIds: [1], homepageCandidateId: 1 };
  const { records } = await derivePilot({ snapshot, directory, classes: expandClassifications(snapshot, plan), plan });
  const site = await privatePilotSite(t, { directory, records, plan });
  assert.ok(site.root.startsWith(`${resolve(directory, "builds")}/`), "private renderer stages assets/content/cache inside its supplied data directory, not a default tmp fixture root");
  assert.ok((await assertPrivatePilotOutput(resolve(site.root, "dist"))).pages > 0);
  assert.equal(records[0].draft.published, false);
  assert.deepEqual(records[0].draft.dimensions, []);
  assert.equal(records[0].ownerFacts.rights, null);
  assert.equal(records[0].ownerFacts.title, null);
  const html = await readFile(resolve(site.root, "dist/artwork/w-0001/index.html"), "utf8");
  assert.match(html, /provisional file mtime/);
  assert.match(html, /Classification unconfirmed/);
  assert.doesNotMatch(html, /Authored connections|"creator"|"@type":"VisualArtwork"|"@type":"Person"/);
});
